name: Java CI with Maven
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Kill existing Chrome processes
      run: |
        pkill chrome || true
    - name: Install Google Chrome
      run: |
        # Install Google Chrome
        wget -q -O - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > google-chrome.deb
        sudo dpkg -i google-chrome.deb
        sudo apt-get install -f
        
        # Generate a unique directory for user data
        USER_DATA_DIR="/tmp/chrome_user_data_$(date +%s)"
        mkdir -p $USER_DATA_DIR
        
        # Start Google Chrome with a unique user data directory
        google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --user-data-dir=$USER_DATA_DIR &
    - name: Build with Maven
      run: mvn test --file pom.xml
